from django.contrib import admin
from .models import *
admin.site.register(Menu)
admin.site.register(Provost)
admin.site.register(Manager)
admin.site.register(AddOns)
admin.site.register(Hall)
admin.site.register(Shift)
admin.site.register(Student)
admin.site.register(Department)
admin.site.register(Feast)
admin.site.register(couponAdd)
admin.site.register(couponMenu)
admin.site.register(feastCoupon)
admin.site.register(soldMenu)
admin.site.register(indCoupon)