# Generated by Django 4.1.1 on 2023-03-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menuType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponapp.shift'),
        ),
    ]
