# Generated by Django 4.1.1 on 2023-03-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0006_student_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='couponapp.manager'),
        ),
    ]
