# Generated by Django 4.1.1 on 2023-03-22 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0009_feast_feastid'),
    ]

    operations = [
        migrations.CreateModel(
            name='couponMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('qt', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponapp.menu')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponapp.shift')),
            ],
        ),
        migrations.CreateModel(
            name='couponAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('qt', models.IntegerField(default=0)),
                ('addOn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponapp.addons')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponapp.shift')),
            ],
        ),
    ]
