# Generated by Django 4.1.1 on 2023-03-22 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0010_couponmenu_couponadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponadd',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='couponapp.hall'),
        ),
        migrations.AddField(
            model_name='couponmenu',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='couponapp.hall'),
        ),
    ]
