# Generated by Django 4.1.1 on 2023-03-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0011_couponadd_hall_couponmenu_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponadd',
            name='processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couponmenu',
            name='processed',
            field=models.IntegerField(default=0),
        ),
    ]
