# Generated by Django 4.1.1 on 2023-03-23 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0012_couponadd_processed_couponmenu_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='feastCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('feast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='couponapp.feast')),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='couponapp.hall')),
            ],
        ),
    ]
