# Generated by Django 4.1.1 on 2023-03-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0013_feastcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feastcoupon',
            name='feast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponapp.feast'),
        ),
    ]
