# Generated by Django 4.1.1 on 2023-03-23 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0015_alter_hall_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='soldMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('qt', models.IntegerField(default=0)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponapp.hall')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponapp.menu')),
            ],
        ),
    ]
