# Generated by Django 4.1.1 on 2023-03-23 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0016_soldmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldmenu',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='couponapp.shift'),
        ),
    ]
