# Generated by Django 4.1.1 on 2023-03-31 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couponapp', '0017_soldmenu_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='indCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponId', models.IntegerField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('couponAdd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='couponapp.couponadd')),
                ('couponMenu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='couponapp.couponmenu')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponapp.hall')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponapp.student')),
            ],
        ),
    ]
